export const EXTENSION_ID = "kfcdhcbocembkiohhbellipdmpmfpebl";
export const SERVER_URL = "https://horizon-testnet.stellar.org";

export const SERVICE_TYPES = {
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  LOAD_ACCOUNT: "LOAD_ACCOUNT",
  GET_MNEMONIC_PHRASE: "GET_MNEMONIC_PHRASE",
  CONFIRM_MNEMONIC_PHRASE: "CONFIRM_MNEMONIC_PHRASE",
  RECOVER_ACCOUNT: "RECOVER_ACCOUNT",
};

export const APPLICATION_STATE = {
  PASSWORD_CREATED: "PASSWORD_CREATED",
  MNEMONIC_PHRASE_CONFIRMED: "MNEMONIC_PHRASE_CONFIRMED",
  MNEMONIC_PHRASE_FAILED: "MNEMONIC_PHRASE_FAILED",
};
