# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  before_all do
    app_store_connect_api_key(
      key_id: ENV.fetch("APPLE_KEY_ID"),
      issuer_id: ENV.fetch("APPLE_ISSUER_ID"),
      key_content: ENV.fetch("APPLE_B64_KEY"),
      is_key_content_base64: true,
      in_house: false #boolean value if team is Enterprise or not
    )
  end
  desc "Sync certificates"
  lane :sync_certificates do
    #read-only disables match from overriding the existing certificates.
    match({readonly: false, type: "appstore", additional_cert_types: "mac_installer_distribution"})
  end
  desc "Create ipa"
  lane :build do
    update_code_signing_settings(
      use_automatic_signing: true,
      code_sign_identity: "Apple Development",
      path: ENV.fetch("XCODE_PROJ_PATH")
    )
    sync_certificates
    gym(
      scheme: "Freighter",
      export_method: "app-store",
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
  end
  desc "Upload to App Store"
  lane :upload do
    deliver
  end
end
