export enum ROUTES {
  debug = "/debug",
  welcome = "/",
  account = "/account",
  viewPublicKey = "/account/view-public-key",
  importAccount = "/account/import",
  accountHistory = "/account-history",
  addAccount = "/add-account",
  signTransaction = "/sign-transaction",
  grantAccess = "/grant-access",
  mnemonicPhrase = "/mnemonic-phrase",
  unlockAccount = "/unlock-account",
  mnemonicPhraseConfirmed = "/mnemonic-phrase-confirmed",
  accountCreator = "/account-creator",
  recoverAccount = "/recover-account",
  recoverAccountSuccess = "/recover-account-success",
  settings = "/settings",
  displayBackupPhrase = "/settings/display-backup-phrase",
  about = "/settings/about",
  preferences = "/settings/preferences",
  security = "/settings/security",
  sendPayment = "/sendPayment",
  sendPaymentTo = "/sendPayment/to",
  sendPaymentSettings = "/sendPayment/settings",
  sendPaymentConfirm = "/sendPayment/confirm",
}
