export enum ROUTES {
  welcome = "/",
  account = "/account",
  signTransaction = "/sign-transaction",
  grantAccess = "/grant-access",
  mnemonicPhrase = "/mnemonic-phrase",
  unlockAccount = "/unlock-account",
  mnemonicPhraseConfirmed = "/mnemonic-phrase-confirmed",
  accountCreator = "/account-creator",
  recoverAccount = "/recover-account",
  recoverAccountSuccess = "/recover-account-success",
  unlockBackupPhrase = "/unlock-backup-phrase",
  displayBackupPhrase = "/display-backup-phrase",
  debug = "/debug",
}
