export const TEST_TOKEN_ADDRESS =
  "CDXBC7NN4ZGB7KSC5HUT2WYM5NZSDNGVMFB7UW353CWFLE5LHPIW3ZNP";

export const USDC_TOKEN_ADDRESS =
  "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA";

export const TEST_M_ADDRESS =
  "MCGORBD5DB4JDIKVIA536CJE3EWMWZ6KBUBWZWRQM7Y3NHFRCLOKYAAAAAAAAAAAAEMC6";
