name: Compile extension PR preview

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Build extension
        runs-on: ubuntu-latest
        steps:
          - uses: borales/actions-yarn@v2.0.0
            with:
              cmd: install # will run `yarn install` command
          - uses: borales/actions-yarn@v2.0.0
            with:
              cmd: workspace extension build # will run `yarn workspace extension build` command
      - name: Zip extension build
        runs-on: ubuntu-latest
        steps:
          - uses: montudor/action-zip@v0.1.0
            with:
              args: zip -qq -r ./extension/build/build.zip ./extension/build
      -name: Report build URL
              run: |
                echo ${{ github.head_ref }}extension/build/build.zip
