name: Cleanup extension PR preview on close

on:
  pull_request:
    types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: pr-release-${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
